# =========================
# APP
# =========================
quarkus.application.name=auth-service
quarkus.http.port=8082
quarkus.http.root-path=/

# =========================
# DATABASE
# =========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:auth_user}
quarkus.datasource.password=${DB_PASSWORD:auth_password}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:astc_auth}}
quarkus.datasource.jdbc.max-size=${DB_POOL_SIZE:10}
quarkus.datasource.jdbc.acquisition-timeout=${DB_ACQUISITION_TIMEOUT:60s}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.database.version=16

# =========================
# GRAPHQL
# =========================
quarkus.smallrye-graphql.root-path=/graphql
quarkus.smallrye-graphql.ui.enable=true

# =========================
# JWT
# =========================
mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=better-auth-verify

smallrye.jwt.sign.key.location=classpath:privateKey.pem
smallrye.jwt.token.header=Authorization
smallrye.jwt.token.schemes=Bearer

quarkus.smallrye-jwt.enabled=true

# =========================
# SECURITY
# =========================
quarkus.http.auth.proactive=false
quarkus.http.auth.permission.public.paths=/graphql-ui,/graphql
quarkus.http.auth.permission.public.policy=permit

# =========================
# FLYWAY
# =========================

# =========================
# DEBUG (IMPORTANTE)
# =========================
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=INFO
quarkus.log.category."org.flywaydb".level=INFO
quarkus.log.category."io.smallrye.jwt".level=INFO

# =========================
# DEV OFF
# =========================
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.test.containers.enabled=false

# =========================
# OPENTELEMETRY
# =========================
quarkus.otel.enabled=false

# =========================
# VERTX (EVENT LOOP)
# =========================
quarkus.vertx.max-event-loop-execute-time=60s

# =========================
# CORS
# =========================
quarkus.http.cors.enabled=true

quarkus.http.cors.origins=/.*/

quarkus.http.cors.methods=GET,POST,OPTIONS

quarkus.http.cors.headers=Authorization,Content-Type,Accept

quarkus.http.cors.access-control-allow-credentials=true
quarkus.log.category."io.smallrye.health".level=WARN
